"use client";

import { BookOpen, MapPin, AlertTriangle, ExternalLink } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { LegalQAResponse } from "@/types/legal";

interface QAResponseProps {
  response: LegalQAResponse;
}

export function QAResponse({ response }: QAResponseProps) {
  return (
    <div className="space-y-6">
      {/* Answer card */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <CardTitle className="text-lg">Answer</CardTitle>
              <CardDescription className="mt-1">
                <span className="flex items-center gap-2">
                  <MapPin className="h-3 w-3" />
                  Jurisdiction: {response.jurisdiction}
                  {response.cached && (
                    <Badge variant="secondary" className="text-xs">
                      Cached
                    </Badge>
                  )}
                </span>
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Original question */}
          <div className="rounded-lg bg-muted/50 p-4">
            <p className="text-sm font-medium">Question:</p>
            <p className="mt-1 text-sm text-muted-foreground">
              {response.question}
            </p>
          </div>

          {/* Answer text */}
          <div className="prose prose-sm dark:prose-invert max-w-none">
            {response.answer.split("\n").map((paragraph, index) => {
              if (!paragraph.trim()) return null;
              return (
                <p
                  key={index}
                  className="text-sm leading-relaxed text-foreground"
                >
                  {paragraph}
                </p>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Sources card */}
      {response.sources.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <BookOpen className="h-5 w-5 text-primary" />
              Sources
            </CardTitle>
            <CardDescription>
              References used to compile this response
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {response.sources.map((source, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 rounded-lg border p-3 transition-colors hover:bg-muted/30"
                >
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-medium text-primary">
                    {index + 1}
                  </span>
                  <div className="flex-1">
                    {source.startsWith("http") ? (
                      <a
                        href={source}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
                      >
                        {source}
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    ) : (
                      <p className="text-sm text-muted-foreground">{source}</p>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Disclaimer */}
      <div className="flex items-start gap-3 rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
        <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
        <div>
          <p className="text-sm font-medium text-yellow-500">
            Legal Disclaimer
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            This response is generated by AI for informational purposes only. It
            does not constitute legal advice and should not be relied upon as
            such. Always consult a qualified legal professional for advice
            specific to your situation.
          </p>
        </div>
      </div>
    </div>
  );
}
